### ISSUE TITLE
HARP matlab interface problem

### ISSUE THREAD

**Issue by zebi90** [stcorp/harp#235]
While using HARP in matlab interface, when i am loading data, they system error says, "Undefined function 'harp_matlab'
for input arguments of type 'char'." Any kind of help will be appreciated.

**Comment by svniemeijer** [comment]
This means that the harp_matlab shared library cannot be found.
Can you please explain what operating system you are using (and whether it is 32bit or 64bit), how and where you installed HARP, and how you configured MATLAB to update the search path?

**Comment by zebi90** [comment]
Dear Sander Niemeiger
Yes it seems like the harp_matlab library is missing.
I am using Windows 10, 64-bit operating system and downloaded HARP from the
following website:
https://github.com/stcorp/harp/releases/tag/1.11.
Regarding the MATLAB configuration to update search path, I have no idea at
the moment, can you please help me in this regard?

Best wishes
Muhammad Zohaib

>

**Comment by svniemeijer** [comment]
Did you install HARP using the .msi file?
Because that is the installer you should use.

It should provide you the harp_matlab library as a `lib\harp\matlab\harp_matlab.mexw64` within your HARP installation directory (`C:\Program Files\HARP` by default). Does that file exist for you?

**Comment by zebi90** [comment]
Dear Sander Niemeiger
Yes I installed HARP using the .msi file from
https://github.com/stcorp/harp/releases/tag/1.11 website, and the
harp_matlab library is present in the designated location. Following error
showed in command window. See the picture below:
[image: image.png]


Best Regards
*Dr. Muhammad Zohaib*

**Comment by svniemeijer** [comment]
You can't attach images to github issues.

Did you follow the steps in the [installation manual](http://stcorp.github.io/harp/doc/html/install.html#installing-the-binary-package-windows) for MATLAB? Mind that you have to do exactly as it says there. Otherwise things won't work.

Also, you might have to logout/login again on Windows to make sure that your system wide PATH settings correctly includes `C:\Program Files\HARP\bin`.

**Comment by zebi90** [comment]
Dear Sander Niemeiger
I had followed the steps in installation manual for MATLAB. I am trying to
read an ".nc" file, whereas the example is for ".asc" file. Could you
please help me with this?
The error in command windows shows as follows:

"Invalid MEX-file 'C:\Program
Files\HARP\lib\harp\matlab\harp_matlab.mexw64':
The specified procedure could not be
found.

Error in harp_import (line 37)
[varargout{1:max(1,nargout)}] =
harp_matlab('IMPORT',varargin{:});

Error in Untitled (line 1)
product1 =
harp_import('C:\Users\HP\Downloads\S5P_NRTI_L2__AER_AI_20201003T072437_20201003T072937_15406_01_010302_20201003T075426.nc');
"

Best Regards
*Dr. Muhammad Zohaib*

**Comment by svniemeijer** [comment]
Can you let me know which MATLAB version you are using?

**Comment by zebi90** [comment]
Dear Sander Niemeiger
I am using MATLAB R2019b.

Best Regards
*Dr. Muhammad Zohaib*

**Comment by svniemeijer** [comment]
We are still building the windows binary installer using a very old version of MATLAB. I will see whether we can upgrade this to a more recent version for our next HARP release. Hopefully that will fix this.

**Comment by zebi90** [comment]
Thank you for your coordination. I hope you will fix soon and let me me.

Best regards

**Comment by svniemeijer** [comment]
We just released a new version of HARP. The windows binary installer is now build against MATLAB 2019b. Could you please check if this version solves the problem for you?

**Comment by zebi90** [comment]
Dear Sander Niemeijer
Thank you for your update. Unfortunately, the problem still persists for
me, I don't know what I am missing. Please help me.

Best Regards

**Comment by svniemeijer** [comment]
Did you install the vs 2015 package as is mentioned in http://stcorp.github.io/harp/doc/html/install.html#installing-the-binary-package-windows ?

If so, could you use the dependency walker as mentioned in https://www.mathworks.com/help/matlab/matlab_external/invalid-mex-file-error.html to find out if it mentions whether a certain file is missing?

**Comment by svniemeijer** [comment]
Do you have any update on this?

**Comment by svniemeijer** [comment]
Closing issue as there is no further update.
